### ISSUE TITLE
Mixed model approach with paired sample design

### ISSUE THREAD

**Issue by hayfre** [HelenaLC/muscat#109]
I have a very similar experimental design to the one mentioned in #12. Is it also possible to include the sample pairing information using the mixed model approach? 

label | sample_id | group_id
C1 | S1 | control 
C2 | S2 | control 
T1 | S1 | treated 
T2 | S2 | treated 

If so, the ∼1+group_id+(1|sample_id) model that is fit for each gene would include the pairing information rather than the unique sample labels. Is this an appropriate model to use or should the pairing information be included in some other way?

**Comment by plger** [comment]
Hi,
It's not appropriate to replace the sample_id with the pair id, but it's possible to use both. Within `muscat` you won't be able to model the "pair effect" as a random effect, but you can model it as a fixed effect while still treating the sample effect as a random variable.
To do this, store the pair id in a variable (e.g. `pair_id`), and then use `mmDS` with `covs="pair_id"`. This will amount to:
`~1+group_id+pair_id+(1|sample_id)`
Pierre-Luc

**Comment by hayfre** [comment]
Hi Pierre-Luc, 
Thank you for your fast and helpful response! I will try it out.
