### ISSUE TITLE
Better home for the DE analysis pipeline 

### ISSUE THREAD

**Issue by LTLA** [HelenaLC/muscat#11]
In [Section 14.3.3](https://osca.bioconductor.org/multi-sample-comparisons.html#putting-it-all-together-1), there is a slightly complex edgeR-based analysis pipeline for cluster-wise pseudo-bulk DE analysis. I would prefer that the users not have to write this out every time they want to do this type of analysis, so I am looking for a loving home for this putative function. 

_muscat_ seems as good a place as any to put it. `pbDS()` almost works as an exact replacement but it lacks a gene filtering step. It also needs some protection against loss of residual d.f. or entire conditions due to removal of samples, see the `try()` block in 14.3.3.

**Comment by HelenaLC** [comment]
Hi Aron,
Happy to modify `pbDS()` to incorporate these (totally sensible) features & for you to make use of our package in the workflow!
Could you specify what you mean by gene filtering? I think we currently just remove all zeros, or genes expressed in lass than a threshold number of cells. What else where you thinking? 
Once that's clarified, I can push an update, and notify you to check if your happy the way things are handled then.

**Comment by HelenaLC** [comment]
Jo Aaron, any updates on this? If `muscat` isn't good enough just let me know and I'll close this issue... But maybe you could still cite us in Chapter 14 ;)

**Comment by LTLA** [comment]
`pbDS` didn't quite do what I wanted, so I ended up making `scran::pseudoBulkDE`.

Main differences are:

- Sample filtering to avoid attempting dispersion estimation on all cell types at once, followed by a separate QL-edgeR analysis of each cell type.
-  Protection against nonsensical design matrices generated by sample filtering.

TBH I didn't want to do that, and I would have preferred if that function lived in **muscat**. But I didn't hear much after our last conversation on this topic so I did what I had to.

**Comment by HelenaLC** [comment]
Hm. I'm confused because I did send you an .Rmd thingy and then never heard back from you. Anyways, agree that having this in `scran` is redundant and unfortunate since we put a lot into package development and documentation. For what it's worth, I believe we don't "attempt dispersion estimation on all cell types all at once", and I did include the sample filtering as you did suggest! So... yeah, if you could mention/cite the package/preprint at least, that'd be appreciated...

**Comment by LTLA** [comment]
> Hm. I'm confused because I did send you an .Rmd thingy and then never heard back from you.

Yes, I forgot about that. Can you make a PR on `sample-comparisons.Rmd` with your approach?

> For what it's worth, I believe we don't "attempt dispersion estimation on all cell types all at once", and I did include the sample filtering as you did suggest! 

Whoops. Yes, I see that now. But we still need protection around loss of rank at:

https://github.com/HelenaLC/muscat/blob/be69b6dcaa0eac415b3787bc3ae634bcc10a7982/R/pbDS.R#L121

I would also like to have `pbDS` take any `SingleCellExperiment` (or in fact, SE), not just something produced by `aggregateData`. It seems the only essential bit is the number of cells, you may consider having an argument like `ncells=metadata(pb)$n_cells` and just skipping cell filtering if `ncells` is `NULL`.

Also, **scran** has some equivalents to `decideTests` that operate on the lists of results. I don't know if you have that here, but if not, just grab those functions and stick them in.

> So... yeah, if you could mention/cite the package/preprint at least, that'd be appreciated...

You are actually cited, twice in fact. But the book hasn't recompiled since the start of the year. This relates to the many, many difficulties with book compilation I discussed with you earlier.
