### ISSUE TITLE
mmDS() and logcounts 

### ISSUE THREAD

**Issue by Nayrouz109** [HelenaLC/muscat#110]
Hello, 

I have a question regarding the use of the `mmDS(method = "dream")`. In the paper, you mention that the method dream was used to fit a MM model on log-normalized data. So does that mean when I run the `mmDS(method=dream)` it will generate logcounts or do I need to specify whether to operate on counts or logcounts ? 

Thanks,

**Comment by plger** [comment]
This is handled internally, you don't need to worry about it. Specifically, `mmDS` will use the count assay in combination with the `sizeFactors()` of the object.

**Comment by plger** [comment]
If `sizeFactors` are empty, they will automatically be computed within `mmDS` (using `computeLibraryFactors()`).

**Comment by Nayrouz109** [comment]
Thank you so much for the clarification, I appreciate it!
