### ISSUE TITLE
Error installing muscat

### ISSUE THREAD

**Issue by MJGGaray** [HelenaLC/muscat#128]
I used this command 

if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

BiocManager::install("muscat")

but every time I tried to install it I got this error:

Package which is only available in source form, and may need compilation of C/C++/Fortran: ‘scuttle’
Do you want to attempt to install these from sources? (Yes/no/cancel) 

no matter if I say yes or no it doesn't work

**Comment by HelenaLC** [comment]
This is not related to `muscat`, but one of its dependencies. I am assuming `BiocManager::install("scuttle")` will also fail. When you say "no matter if I say yes or no it doesn't work", you should check what is causing `scuttle` to not install cleanly (and fix it); then reattempt installing `muscat`. As the error states, `scuttle` is only available from source. So depending on what OS you are using, you need to make sure you meet software requirements for compilation (e.g., [here](https://cran.r-project.org/bin/macosx/tools) is some info for macs).
