### ISSUE TITLE
How do I use muscat if my single cell data comes from different datasets with clear batch effects?

### ISSUE THREAD

**Issue by WyzhaoJo** [HelenaLC/muscat#130]
My single cell data comes from different datasets. There are clear batch effects.  How do I remove batch effects in pseudobulk analysis?Thanks a lot!

**Comment by plger** [comment]
Use the `design` argument:

```
mm <- model.matrix(~batch+group)
res <- pbDS(pb, design=mm)
```

If you have a complex design you might also want to use the `contrast` or `coef` argument of `pbDS` to specify what specific effect you want to test. If you need more info on that, google or check chapter 9 of `limma::limmaUsersGuide()`.

**Comment by WyzhaoJo** [comment]
Thanks!!I'll try it tomorrow!!
