### ISSUE TITLE
Loss of clusters during pbDS

### ISSUE THREAD

**Issue by bkheira** [HelenaLC/muscat#132]
Hi everyone, 

I am analyzing an immune dataset with 11 clusters. 
![image](https://github.com/HelenaLC/muscat/assets/115224647/fbe5e9f6-005d-4c63-88ac-3e87626dce68)

When I run pbDS on this dataset, the results are available for only 9 clusters, even if I set the min_cells parameter at 1. 
![image](https://github.com/HelenaLC/muscat/assets/115224647/cb53ee20-a042-4b21-bb49-299d6f650d0c)

I am missing the B cells, which I am interested in, and the fibroblasts.

Do you know if there is something I am missing ?

Many thanks
Kheira

**Comment by HelenaLC** [comment]
Could you post the output of `table(sce$kid, sce$sid)` and `table(sce$sid, sce$gid)` or something like that? Where s/k/g = sample,cluster,group; thanks!

**Comment by bkheira** [comment]
I tried adding the parameter "filter" on genes and now I have all my clusters in the results of pbDS. I don't know why but some low gene expression in the B cell cluster was probably not allowing it to be in the results. 

Many thanks Helena for your help and for this package.
