### ISSUE TITLE
aggregateData does not return colData

### ISSUE THREAD

**Issue by Nayrouz109** [HelenaLC/muscat#135]
Hello, 

I have a single cell sce object and i used aggregateData() to generate a pseudobulk matrix as follows: 

```
pb <- muscat::aggregateData (sce,
                    assay = "counts", 
                    fun = "sum",
                    by = c("patientID")
 )
```

However, when i want to have a look at the "new" metadata/coldata for the pseudobulk matrix using `SummarizedExperiment::colData(pb)` i get this 

> DataFrame with 52 rows and 0 columns

**Comment by PeteHaitch** [comment]
FYI an option for you might be `scuttle:: aggregateAcrossCells()`, which has the `coldata.merge` parameters to enable you to specify how to merge the colData fields (because it's not always obvious how it should be done automatically).
