### ISSUE TITLE
No de genes with pseudobulk approach

### ISSUE THREAD

**Issue by bio-la** [HelenaLC/muscat#14]
Hi, thanks for the great tool, it's really easy to streamline analyses with it and I will definitely explore all the customization options available for my projects!

I was hoping you could give me some pointers on what (else) to test for my data. I have integrated and clustered 100k cells into 47 cell states, each of these has 2 experimental condition and 2 tissues (so 4 grouping variables). I have 6 patients, 3 per condition, and each patient will have both tissues sampled. I performed differential expression at the single cell level using edgeR pretty much as suggested in Charlotte Soneson's paper, but I was hoping to have some back-up results pseudobulking the data, given how some clusters will inevitably have less cells and a lot of false positives. 
Unfortunately, when I summarize the raw counts for each of the clusters into patient*tissue*condition (and i would have almost always 3 pseudobulks for each tissue*condition combination for each of the 47 states) I don't have a single gene differentially expressed!
I tried both the osca-book approach and yours, and i have the same results (not surprisingly,as they're doing more or less the same thing as aaron points out #11) .

do you think that having so little replicates (3 individuals) which may as well be very different one from another might be my main problem? 
is there any other way i could break the clusters into smaller chunks, would it be sensible to randomly subsample each cluster into k smaller ones to have more pseudobulks? (something similar to the deconvolution normalization strategy used in scater/scran) 
I don't want to start doubting about the whole upstream strategy, but if heterogeneity is the problem then the need for some backup data for my single cell differential expression analysis is more than justified!

thanks again!

**Comment by markrobinsonuzh** [comment]
Dear @bio-la 

Have you tried any differential abundance analyses? This has not been a main aspect of `muscat` because we were focused on state changes, but given that you have so many clusters (at least for some of our datasets, 47 seems a lot), it could be that some clusters are differentially abundant between conditions. For this, I would generate a count table of clusters by samples and run the same style of RNA-seq-like differential analysis, but on the cluster counts. Pay attention here to normalization, as well.

It could also be that you've over-clustered too much? You mentioned that you've "clustered into 47 cell states". Our thinking is that you generally want to only cluster into cell types (assuming that type is the primary signature and state is secondary) and analyze these at the type level with pseudobulks. At this point, we don't have a good sense of the sweet spot between resolution of clustering and power to detect changes (more cells aggregated over typically gives more power).

You also ask what "might be [the] main problem?". I guess you shouldn't rule out that there are not strong transcriptional changes in your dataset. Maybe no changes is a good result?

Hope that helps,
Mark

**Comment by bio-la** [comment]
Hi Mark,
thanks for the quick reply. 
I agree that 47 clusters is a lot. We arrived at this stage after splitting the entire dataset into 3 main cell types, and further clustering each into smaller groups. I agree that it may be the case that this strategy penalized us in terms of power for the differential expression. 
A thought would be to re-group some of the clusters into bigger groups and re-test the differential expression, although some of the smaller clusters would be too different from the others to be aggregated with any of the other cell states. (one also wonders how much one is willing to believe in such small groups of cells anyway!) This problem is common to many other datasets and it's, as you pointed out, a matter of finding the right balance between detection of "new cell states" vs grouping the cells into broader states which will definitely ensure a higher power for detection of expression changes. 
I can only assume that as the available datasets become bigger with more individuals sampled, we'll narrow down the set of variables to keep at bay to find such sweet spot as mentioned above.
Thanks for suggesting the abundance analysis, I will definitely test that too.
With best wishes,
fabiola

**Comment by pariaaliour** [comment]
Hi,
I have the same problem as mentioned here. However, my clusters are not that many, I have 20 and 28 clusters in two of my datasets. I was wondering if you have any suggestion. In my case, I only have DE in two cell type. But when I did DE using Seurat FindMarkers function (at single cell level) I had way more DE genes.
Could you also please point me to a tutorial which elaborate more on cell level analysis?
Many thanks,
Paria

**Comment by HelenaLC** [comment]
@pariaaliour `muscat` and `Seurat`'s `FindMarkers` are not for the same task. 
- `muscat` is designed for (what we term) differential state (DS) analysis: testing for cross-condition DE at the subpopulation level (e.g., which genes are differential within cluster X and across conditions)
- `FindMarkers` is designed for 'classical' DE analysis: testing for expression changes between clusters (e.g., which genes are differential between cluster X and Y)
So I am a little confused by the mention of `FindMarkers` in this context. Perhaps you could clarify what your experimental design is (e.g., sample, groups, other) and what you are trying to achieve.

**Comment by pariaaliour** [comment]
I see. but with this function I do compare two status within each cluster at cell level. I wanted to try Muscat at cell level as I think it's more reliable to see if I willl have more DEGs. 
![image](https://user-images.githubusercontent.com/52675953/224487836-dff25b03-40ca-4531-9d75-27491b9b68ce.png)
I have 10 individuals (two regions of each individuals) and 110k nuclei. I'm. not sure if increasing sample size would make any differences.
Thanks
Paria
