### ISSUE TITLE
Error in `simData`: attempt to extract more than one element

### ISSUE THREAD

**Issue by milanmlft** [HelenaLC/muscat#15]
Hi there,

Thank you for the super nice package! 
I'm trying to simulate some data based on the Kang dataset, which I loaded through ExperimentHub as in the muscat vignette. 

It seems there is an issue with `simData`, which gives me the following error:

```
Error in normalizeDoubleBracketSubscript(i, x, exact = exact, allow.NA = TRUE,  : 
  attempt to extract more than one element
```

I think the problem might be with this [line](https://github.com/HelenaLC/muscat/blob/be69b6dcaa0eac415b3787bc3ae634bcc10a7982/R/simData.R#L162), where the `grep` call returns multiple items if some of the sample names are identical to the prefixes of others (e.g. "ctrl101", "ctrl1015" and "ctrl1016").

I noticed there might already be some fixes for this in the `fix_sim` branch. Is it possible to install the package from that branch? Alternatively, when do you think these fixes will be implemented in the Bioconductor release?

Thanks a lot!

**Comment by HelenaLC** [comment]
Yes, identical prefixes would indeed cause this error. The `fix_sim` code fixes this as you pointed out. 
1) You can install the `fix_sim` branch via `devtools::install_github("HelenaLC/muscat", ref = "fix_sim")`.
2) The changes from that branch (which are a major update to almost all of the package...) will become available "officially" with the next Bioconductor release (v3.11) -> https://www.bioconductor.org/developers/release-schedule
