### ISSUE TITLE
Applying muscat's DS analysis on CyTOF data

### ISSUE THREAD

**Issue by MikhaelManurung** [HelenaLC/muscat#19]
Hello,

Is it okay to do the cell-level DS analysis on CyTOF data? Is there any caveat that I should be aware of when using this package for CyTOF?

Thanks for your time!

**Comment by markrobinsonuzh** [comment]
@MikhaelManurung Interesting question. In principle, yes, there is a lot of overlap b/w DS analyses on scRNA-seq and CyTOF. For CyTOF, you might consider also the `diffcyt` package, which operates analogously to the pseudobulk approaches in `muscat` (main difference: scRNA-seq count are used in count models, whereas the CyTOF ion counts are typically transformed and used in continuous models). But you specifically asked for "cell-level DS", which probably means the mixed models and if the CyTOF is transformed in a reasonable way (e.g., `asinh(x/5)`), it should work pretty well. However, I don't know if you get much advantage over the aggregation approach of `diffcyt` and the compute cost is higher.

Hope that helps, Mark

**Comment by MikhaelManurung** [comment]
@markrobinsonuzh thanks for taking the time to answer! Yes, I have used `diffcyt` before for DS analysis. However, as the package aggregates marker expression to its median, I find it very not sensitive in detecting minute changes. Earth mover's distance is a good alternative, but I find it hard to interpret the result.
