### ISSUE TITLE
calcExprFreqs returns NA if single sample_id not present in cluster

### ISSUE THREAD

**Issue by dpcook** [HelenaLC/muscat#20]
Hi Helena--thanks for your work on the package! It's been a fantastic help for these types of experimental designs.

I'm getting NAs in the group_id.frq columns of `resDS()` when `frq = TRUE` if any of the sample_ids don't have cells for a given cluster. The frq column for the specific sample_id is also NA for the cluster, which seems like a logical return to disambiguate between this case and when there are cells, but with zero expression.

It would be nice to be able to use the group_id.frq columns for filtering. Would a better way to handle this be to calculate the frequency even if a sample is absent?

Thanks!

David

**Comment by HelenaLC** [comment]
Thanks for bringing this to my attention! I've fixed this in my local development branch alongside some proper unit-testing, and am closing this issue for now- the changes will be in with the next release!

**Comment by browaeysrobin** [comment]
Hi @HelenaLC 

Should this already be fixed now or is this problem still present? If I run `calcExprFreqs(sce, assay = "counts", th = 0)`, returned group fractions are NaN for clusters that have 0 cells for at least 1 group (both via the bioconductor version and the development branch)
