### ISSUE TITLE
questions regarding setting up contrasts, # DGE genes

### ISSUE THREAD

**Issue by kmh005** [HelenaLC/muscat#23]
Hello,

First, thank you for extending the functionality of edgeR to SC with a clear, cogent approach, and adding in the feature of mixed models.

We have questions about setting up a contrast matrix or using other methods, and evaluating the length of adjusted p-value <= 0.05 genes.

We have two conditions, A and B, and treatments of 0 (no treatment), 1 (restorative treatment), and 2 (null treatment). The crux of the matter is: can we cause restoration from A.Treat1 towards the expression pattern of B.Treat0? Condition A is a heavily-mutated version of Condition B, and A.Treat0 reflects an already-perturbed (but natural) steady-state. However, there is only the 1 steady-state (Treat0) measurement for both treatments 1/2, which is why we are open to suggestions. It is intuitive enough to compare Treat 1v0 and 2v0 for each condition.  Where we come into issues is trying to compare the effects of treatment between Treat1 and Treat2 with respect to Treat0.  Then, we are trying to form a comparison linking A.Treat1 to B.Treat0 while controlling for the null treatment A.Treat2, like the Placebo in the edgeR user manual section 3.3.1.

Here is a condensed version of the workflow, after aggregating on sum; counts.

```
data.frame(Condition, Treatment)
Condition Treatment
1         A    Treat0
2         A    Treat1
3         A    Treat2
4         B    Treat0
5         B    Treat1
6         B    Treat2

condition.treatment <- paste(Condition, Treatment, sep=".") #this is group_id
condition.treatment
[1] "A.Treat0" "A.Treat1" "A.Treat2" "B.Treat0" "B.Treat1" "B.Treat2"

design <- model.matrix(~0+condition.treatment)
colnames(design) <- condition.treatment

my.contrasts <- makeContrasts(A12 = A.Treat1-A.Treat2,
                              A120 = (A.Treat1-A.Treat2)-A.Treat0,
                              A1200 = (A.Treat1-A.Treat2)-(A.Treat0 - A.Treat0),
                              A10 = A.Treat1 - A.Treat0,
                              A20 = A.Treat2 - A.Treat0,
                              A102B0 = (A.Treat1 - A.Treat0) - (A.Treat2 - B.Treat0),
                              A120B0 = (A.Treat1 - A.Treat2) - (A.Treat0 - B.Treat0),
                              A0B0 = A.Treat0 - B.Treat0,
                              levels=design)
my.contrasts
          Contrasts
Levels     A12 A120 A1200 A10 A20 A102B0 A120B0 A0B0
  A.Treat0   0   -1     0  -1  -1     -1     -1    1
  A.Treat1   1    1     1   1   0      1      1    0
  A.Treat2  -1   -1    -1   0   1     -1     -1    0
  B.Treat0   0    0     0   0   0      1      1   -1
  B.Treat1   0    0     0   0   0      0      0    0
  B.Treat2   0    0     0   0   0      0      0    0

d<-pbDS(pb, method="edgeR", design = design, contrast = my.contrasts, min_cells=1)

d$table$A12$ClusterA %>% filter(p_adj.loc <= 0.05) %>% nrow()
[1] 1

d$table$A120$ClusterA %>% filter(p_adj.loc <= 0.05) %>% nrow()
[1] 15442

d$table$A10$ClusterA %>% filter(p_adj.loc <= 0.05) %>% nrow()
[1] 63

d$table$A20$ClusterA %>% filter(p_adj.loc <= 0.05) %>% nrow()
[1] 21

d$table$A102B0$ClusterA %>% filter(p_adj.loc <= 0.05) %>% nrow()
[1] 63

d$table$A120B0$ClusterA %>% filter(p_adj.loc <= 0.05) %>% nrow()
[1] 63

d$table$A0B0$ClusterA %>% filter(p_adj.loc <= 0.05) %>% nrow()
[1] 173

d$table$A120$ClusterA %>% nrow()
[1] 17652
```

A1200 does not appear like the appropriate setup as per contrast matrix as expected. So is A120 technically valid?  Is the comparison chaining conditions A and B constructed properly (A102B0)?

In our hands, the simple pairwise A 1v2 returns 1 gene (MAST returns 75 q <= 0.05), which is unfortunately low. When Treat0 is added to the model A120, 15k of 17k genes are significant, which leads us to investigate this further.  The top "hits" are highly indicative of the underlying biology, but the p/local/global values are "0" for about 4.5k terms.  Our model incorporating conditions A and B (A1-A0)-(A2-B0) yields 63 terms, which is the model we are the most concerned with constructing correctly.  The (A1-A2)(A0-B0) does return the same results, as expected, since the contrast matrix is the same.  The no-treatment A0/B0 contrast yields 173 genes (MAST: 500). As further sanity checks: aggregating by mean produces A12 0; A120 10k genes, sum Condition B B12 3; B120 15440 genes.

Your advice and any other ideas most appreciated, and please let me know if you'd like any additional info.

Thanks,
kmh005

**Comment by HelenaLC** [comment]
A natural way to account for the interplay between condition and treatment in your setup would be to use an interaction term, i.e. `~ condition * treatment`, which will yield coefficients of the form `condA:treat1, condA:treat2, ...`.

**However**, the biggest problem we see is that you have no replicates, i.e., there is *not enough data to fit the model* above (there's only one sample per condition-treatment combination). Two more pointers:

* We recommend you have a look at 
`edgeR` user guide, section 2.11: "What to do if you have no replicates" (https://www.bioconductor.org/packages/release/bioc/vignettes/edgeR/inst/doc/edgeRUsersGuide.pdf) 
* Lastly, this question is not directly related to `muscat`, and it might be worth getting some insights from, e.g., the Bioconductor support forum (with tags `edgeR`/`DESeq2`) where there's a large community that could give advice, not just us (https://support.bioconductor.org).
