### ISSUE TITLE
Requirement on R version for installation

### ISSUE THREAD

**Issue by drychkov** [HelenaLC/muscat#27]
Hi,

Currently, there is a requirement of the R version: Depends: R (>= 4.0).
Is it possible to lower to at least current stable version 3.6.3? Or it has dependences from the 4th version?

Thanks!

**Comment by HelenaLC** [comment]
You can install the package from Bioc directly using R 3.6 via `BiocManager::install("muscat", version = "3.10")`. The GitHub branch is currently under development for the upcoming Bioc 3.11 / R 4.0 release end of this month.
