### ISSUE TITLE
pbMDS plot error

### ISSUE THREAD

**Issue by priyamnarain** [HelenaLC/muscat#28]
Hi I get the following error: If you guide how to solve this?

> (p <- pbMDS(pbs) + scale_shape_manual(values = c("ZT2" = 17, "ZT13" = 8)))

Error in .check_pbs(x, check_by = TRUE) : 
!is.null(ei <- metadata(pbs)$experiment_info) is not TRUE

**Comment by HelenaLC** [comment]
`pbs` should have a slot `metadata(.)$experiment_info`, which was created by `prepSCE`- can you check whether `metadata(.)$experiment_info` exists *before* aggregation, so in the SCE used by `aggregateData` to compute `pbs`?

**Comment by priyamnarain** [comment]
This is sorted. Thanks.
