### ISSUE TITLE
is there an R3.6 version for muscat?

### ISSUE THREAD

**Issue by crazyhottommy** [HelenaLC/muscat#33]
Hi,
the current installation from github requires R4.0. do you have a version of muscat for R3.6?
I am not ready to upgrade my R yet.

Thanks!
Tommy

**Comment by markrobinsonuzh** [comment]
Yes, there is a 1.10.x series of `muscat` that will run on R 3.6:
https://www.bioconductor.org/packages/3.10/bioc/html/muscat.html

.. but also there has been a ton of changes in that period, so I'm sure @HelenaLC would recommend that you work with the 1.12.x series .. and in general, we have simply resigned ourselves to the fact that we need to be up and running in a multi-version environment. Things move so fast, it's hard to operate without this flexibility (e.g., I have projects running on R 3.6.x and 4.0.x simultaneously).

Best, Mark

**Comment by crazyhottommy** [comment]
Thanks Mark! I will try the R4.0 version within a container then.
