### ISSUE TITLE
Speed up aggregateData()

### ISSUE THREAD

**Issue by HelenaLC** [HelenaLC/muscat#48]
- replace internals with `scuttle`'s `sumCountsAcrossCells`, which is much faster  
(based on `colsum` vs. current `data.table` -> `split` -> `map` -> `rowSums`)

**Comment by wmacnair** [comment]
Hey, just checking that this hasn't been forgotten - at present it is not fixed in either master or devel.

I'm currently using my own implementation based on `scuttle::summarizeAssayByGroup`.

Thanks!

**Comment by HelenaLC** [comment]
Fixed in version 1.5.1 available through GitHub master branch now, and Bioc devel in a couple days.
