### ISSUE TITLE
`runDS` not found

### ISSUE THREAD

**Issue by lpantano** [HelenaLC/muscat#5]
Hi!

thanks for developing this package, so glad is out there.

I am having an issue when I am trying the tool. When I am at the step of `runDS`, it says it cannot find the function. I tried to see if it was exported by another package, but I cannot see it in the NAMESPACE.

Can you help me with this?

thanks!

**Comment by HelenaLC** [comment]
Hey, sorry about this! The function name has been changed to `pbDS` for pseudobulk methods, and `mmDS` for mixed models. If `runDS`appears anywhere in examples ect. it is a mistake.

**Comment by lpantano** [comment]
cool, I was following the vignette. Thanks!

**Comment by HelenaLC** [comment]
Vignette update coming up- possibly today. I hope ;) ... Closed this issue now; but thanks for reminding me I need to go through all examples & completely remove `runDS`!
