### ISSUE TITLE
Tests for three groups

### ISSUE THREAD

**Issue by yuyingxie** [HelenaLC/muscat#54]
I am running a experiement with three groups (Healthy, moderate and severe). How should I do the global test for the null hypothesis that these three groups have the same effect?

Also, how can I do the pairwise test like healthy vs moderate, moderate vs severe, etc?

Thanks so much for your help.

**Comment by plger** [comment]
See my answer to your other issue ( #55 ) regarding the global test. These two questions could have been put in the same issue, so I'll close this one.
For pairwise tests you can simply test using each coefficient value (see the code in the other issue to get the coefficient names or order).
Alternatively, if you use `pbDS` instead you'll have the contrast-base specification at your disposal.
