### ISSUE TITLE
Proposal: rename the example `sce` dataset

### ISSUE THREAD

**Issue by milanmlft** [HelenaLC/muscat#60]
I've noticed that __muscat__ contains an example dataset object named `sce`, which becomes available immediately after loading __muscat__:

``` r
try(sce)
#> Error in try(sce) : object 'sce' not found

library(muscat)
sce
#> class: SingleCellExperiment 
#> dim: 1267 1556 
#> metadata(1): experiment_info
#> assays(2): counts logcounts
#> rownames(1267): HES4 ISG15 ... CSTB PRMT2
#> rowData names(2): ENSEMBL SYMBOL
#> colnames(1556): ATCATGCTGCGTAT-1 GTACGAACTGTCAG-1 ... TCAAGGTGGAATGA-1
#>   GAATGGCTAAACAG-1
#> colData names(3): cluster_id sample_id group_id
#> reducedDimNames(1): TSNE
#> mainExpName: NULL
#> altExpNames(0):
```

This might lead to confusion though, since `sce` is a commonly used name for *SingleCellExperiment* objects in many analyses.
For example, if I didn't create an `sce` before, I would expect this to fail:

```r
## In a new R session
library(muscat)

## No `sce` explicitly created but this still works:
prepSCE(sce)
#> class: SingleCellExperiment 
#> dim: 1267 1556 
#> metadata(1): experiment_info
#> assays(2): counts logcounts
#> rownames(1267): HES4 ISG15 ... CSTB PRMT2
#> rowData names(2): ENSEMBL SYMBOL
#> colnames(1556): ATCATGCTGCGTAT-1 GTACGAACTGTCAG-1 ... TCAAGGTGGAATGA-1
#>   GAATGGCTAAACAG-1
#> colData names(3): cluster_id sample_id group_id
#> reducedDimNames(1): TSNE
#> mainExpName: NULL
#> altExpNames(0):
```

but it doesn't because it's using the `sce` object from __muscat__.

I can confirm that this is a common source of confusion when using __muscat__ and I can imagine that it might complicate development / maintenance as well since `sce` is also often used as a variable name in various functions.

__Proposal__: might it be an idea to rename the example `sce` to `example_sce` or something like that? If you agree, I'm certainly willing to contribute through a PR.

Thanks a lot!

**Comment by HelenaLC** [comment]
Done.
