### ISSUE TITLE
pbDS() makes error:  identical(assayNames(pbs), rownames(n_cells)) is not TRUE

### ISSUE THREAD

**Issue by dmsalsgh97** [HelenaLC/muscat#62]
Hi,
I have scRNA-seq data with 2 conditions(wt/stim) with 3 replicates. (total = 6 sample)
I want to see my single-cell data can be used as bulk data, so I aggregated it from the seurat_object without cluster_id.

```
sce <- as.SingleCellExperiment(my_seurat_object)
Epi.combined.sce <- prepSCE(sce , 
                            kid = NULL, # I have no cluter id
                            gid = "group_id",  # group IDs (ctrl/stim)
                            sid = "orig.ident", drop = TRUE)   

pb_sum <- muscat::aggregateData(sce , fun = "sum", by=c("sample_id"), assay='counts')
df_pb_sum <- as.data.frame(assay(pb_sum))
```

by adding raw counts of my_seurat_object, I double-checked that muscat's aggregateData worked well.
```
> pb_sum
class: SingleCellExperiment 
dim: 31053 6 
metadata(2): experiment_info agg_pars
assays(1): ''
rownames(31053): Xkr4 Gm1992 ... Vmn2r122 CAAA01147332.1
rowData names(0):
colnames(6): 2-H_Epi 2-L_Epi ... 4-H_Epi 4-L_Epi
colData names(0):
reducedDimNames(0):
altExpNames(0):
```

But when I tried to run pbDS( ) on pb_sum, it generates Error like below:
```
> pbDS(pb_sum)
Error in .check_pbs(pb, check_by = TRUE) : 
  identical(assayNames(pbs), rownames(n_cells)) is not TRUE
```

I guess this error must  be due to my pb_sum not has $n_cells on metadata..
```
> metadata(pb_sum)
$experiment_info
  sample_id group_id n_cells
1   sample2_wt    wt  9232
2   sample3_wt    wt  9768
3   sample4_wt    wt  7673
4   sample2_mm    mm  11344
5   sample3_mm    mm  8492
6   sample4_mm    mm  6010

$agg_pars
$agg_pars$assay
[1] "counts"

$agg_pars$by
[1] "sample_id"

$agg_pars$fun
[1] "sum"

$agg_pars$scale
[1] FALSE
```

Using muscat without any cluster number isn't possible?

**Comment by HelenaLC** [comment]
Could you tried adding a mock cluster_id (eg “foo” or “1” and re-running? It could indeed be that this case is currently not handled well, as muscat was written for DS (cluster-level) not classical bulk DE analysis. I will look into it! But it’d be good to test whether it’d work with one cluster.

**Comment by dmsalsgh97** [comment]
I tried your advice by adding mock cluster_id on myseurat object, and pbDS() works well! 
My original thought was to use scRNA-seq data as a bulk data because of the difficulties of sample prep procedure...

I'll try it! thanks for the prompt reply and for developing a valuable pipeline :)

**Comment by dmsalsgh97** [comment]
I think this "adding mock cluster id" is solved this issue
Thanks for @HelenaLC!

**Comment by ybaeus** [comment]
```{R}
sobj_subset.sce <- as.SingleCellExperiment(sobj_subset)
sce <- prepSCE(sobj_subset.sce,  
               kid = "final_cell_type",  # -> cluster_id celltype_sample
               sid = "case_position_per_slide", # -> sample_id
               gid = "run_tissue_name") # -> group_id

pb <- aggregateData(sce, fun = "sum", 
                    by = c("group_id")) 
ds_pb <- pbDS(pb)
```

Caused the same error #62.
_Error in .check_pbs(pb, check_by = TRUE) : 
  identical(assayNames(pbs), rownames(n_cells)) is not TRUE_

```
# FYI
> pb@metadata
$experiment_info

$agg_pars
$agg_pars$assay
[1] "logcounts"

$agg_pars$by
[1] "group_id"

$agg_pars$fun
[1] "sum"

$agg_pars$scale
[1] FALSE
```

Could you also look into this problem?

**Comment by HelenaLC** [comment]
I can't say what's causing the issue from the output printed above, however:

The above analysis is not what `muscat` is designed to do. I see that the `logcounts` assay is being used, and you are aggregating `by="group_id"` with `sum="sum"`. Put into words, you are *summing* each genes *expression* across all cells in a *group*. There are a couple approaches (see `?pbDS`), however, the default would be to sum the counts by sample-cluster; or, say, average expression values. Please check out the vignette and follow what's demonstrated there or, better, read up in the publication introduction/first results section to understand the general approach.

**Comment by ybaeus** [comment]
Thanks for the reply, @HelenaLC!
I was a bit impetuous asking you things at that moment. I was just testing with 'group-id', 'sample-id', and 'cluster-id' and checking what's differences thoroughly from your R source. Yet, using the default solved the issue. Thanks!
