### ISSUE TITLE
Muscat doesn't work with one cluster anymore

### ISSUE THREAD

**Issue by VPetukhov** [HelenaLC/muscat#68]
In a [recent update](https://github.com/HelenaLC/muscat/commit/6c6ac7235d9af2d38b7740bfb3ac0f5c0d0d999f#diff-4a471856f16c0521bff826e6ecd27570a35c8939375208e7fb52ac2db0811c62R96), you started removing variables from the object if there is only one level. As the result, if there is only one cluster in the reference data, [this `table` call](https://github.com/HelenaLC/muscat/blob/master/R/prepSim.R#L145) fails, as one of the arguments is `NULL`. Is it possible to avoid such filtering?

**Comment by HelenaLC** [comment]
I believe this has been fixed - could you confirm?

**Comment by VPetukhov** [comment]
Indeed, it works now. Thank you, @HelenaLC !
