### ISSUE TITLE
Different global and local p value for testing only 1 cluster

### ISSUE THREAD

**Issue by wanghao98** [HelenaLC/muscat#69]
Hi, when I subset my data so the singlecellExperiment object contains only 1 cluster, the resulting p_adj.loc and p_adj.glb are different (which should be the same if we only have one clusters?). 
Any idea or suggestions?
Thanks!

**Comment by HelenaLC** [comment]
Which R/Bioc/muscat version are you using? There was indeed a bug previously, where p-values were adjusted using `"BH"` and `"holm"` as correction method, respectively. Now, both local and global adjustment should use `"BH"`, and adjusted p-values should indeed be the same when there's only one cluster.

**Comment by wanghao98** [comment]
Thanks for the reply! I just checked that my current version is 1.4. I'll try to update it and see if that fixes the problem.
Thanks again!

**Comment by HelenaLC** [comment]
Closing for now. Feel free to reopen should the issue persist!
