### ISSUE TITLE
Trouble loading data from GSE96583

### ISSUE THREAD

**Issue by meghamsh738** [HelenaLC/muscat#75]
I wanted to replicate the results in the paper. However, I cant figure how to load the data into variable sce. Also unlike the 10x genomics output I know of (containings barcodes, matrixes, and features), this dataset contains only barcodes and matrix in a "Microsoft access table shortcut".

**Comment by HelenaLC** [comment]
The data has been made available has an SCE through Bioc’s ExperimentHub. Please see the muscData package vignette on Bioc for how to load the data in a few lines!
