### ISSUE TITLE
Error in x[[1]] : subscript out of bounds when running pbDS()

### ISSUE THREAD

**Issue by Yale73** [HelenaLC/muscat#78]
Hi muscat team,

Thanks for such a great DEGs package. It's so fast and gets more exciting results than other methods. 

I am working on single-cell data. When I ran grouped samples, everything went well. But when I ran one sample vs many normals, then I was blocked at `pbDS()` and got `Error in x[[1]] : subscript out of bounds`. I am sure I did the filter with genes and cell numbers. The error trace showed there is something wrong with` .p_adj_global(res$table)`

```
>AD1 = pbDS(pb, design = mm, contrast = contrast_170, method = "edgeR")
1..10..11..12..13..14..15..16..17..18..19..2..20..21..22..23..24..25..26..27..28..29..3..30..31..32..33..34..35..36..37..38..39..4..40..41..5..6..7..8..9..Error in x[[1]] : subscript out of bounds

Enter a frame number, or 0 to exit   

1: pbDS(pb, design = mm, contrast = contrast_170, method = "edgeR")
2: .p_adj_global(res$table)
```
my `contrast_170 <- makeContrasts("170-NML", levels = mm)`.

Can you help me with it?

Thanks,
Yale

**Comment by HelenaLC** [comment]
Dear Yale, thanks for the encouraging words.

Unfortunately, I cannot quite follow / reproduce the issue from this. What do you mean by "one sample vs. many normal"? Certainly, this will not work, as you require at least two replicates per group to perform DE - but I might be misunderstanding... 

Any clarification or, ideally, a reproducible example that gives the error would be appreciated.

**Comment by Yale73** [comment]
Hi Helena @HelenaLC,

Thanks for your reply and sorry for the unclear. I think you have answered me, as I have one replicate in one group. 

We have 6 replicates in the lesion group (170, 171, 172, 173, 174, 175) and 7 normals in the control group. We want to use muscat to run DEGs between an individual replicate in the lesion group and 7 normals. Then we can compare 6 DEGs from each lesion and find the conservative genes. It seems we can not run it because of one replicate in the lesion group, right?

I thought maybe cell-level analysis works, but there is no `contrast` and I don't which samples are used to run the DEGs . Also, I ran a different error   
```
mm <- mmDS(sce, method = "nbinom")
Error in mmDS(sce, method = "nbinom") : 
  No cluster has at least 2 samples with at least 10 cells.
```

The following is my whole script.

```
sce <- as.SingleCellExperiment(SeuratObject)
sce = sce[, sce$dis%in% c("Lesion", "NML")] #### we have many groups and only subset these two

sce <- sce[rowSums(counts(sce) > 0) > 0, ]
qc <- perCellQCMetrics(sce)
ol <- isOutlier(metric = qc$detected, nmads = 2, log = TRUE)
sce <- sce[, !ol]
sce
sce <- sce[rowSums(counts(sce) > 1) >= 10, ]
sce
sce <- computeLibraryFactors(sce)
sce <- logNormCounts(sce)

### drop off empty donor2
sce$donor2 <- droplevels(x = sce$donor2) ### donor2 is a factor with individual sample ID and combined normal ID.

### remove clusters with less than 3 cells in at least one group.
cluster_prop = table(sce$donor2, sce$ID)
cluster_prop <- as.data.frame(cluster_prop)
zero_cluster = cluster_prop[cluster_prop$Freq<= 3, ]

sce2 = sce[, !(sce$ID %in% zero_cluster$Var2)]
sce2$ID <- droplevels(x = sce2$ID)

sce <- prepSCE(sce2, 
               kid = "ID", # subpopulation assignments
               gid = "dis",  # group IDs (ctrl/stim)
               sid = "donor2",   # sample IDs (ctrl/stim.1234)
               drop = TRUE)

##pb <- aggregateData(sce, assay = "counts", fun = "sum", by = c("cluster_id", "sample_id"))

contrast_170<- makeContrasts("170-NML", levels = mm)
contrast_171<- makeContrasts("171-NML", levels = mm)

Rash1 = pbDS(pb, design = mm, contrast = contrast_170, method = "edgeR") ###Here I ran the error.
Rash2 = pbDS(pb, design = mm, contrast = contrast_171, method = "edgeR")


```
Thanks,
Yale

**Comment by andrewjkwok** [comment]
Hi @HelenaLC - was just wondering there was any update and whether anything else I could provide might be of help?

**Comment by andrewjkwok** [comment]
Hi @HelenaLC - wanted to check in again to see if there were any updates?

**Comment by epurdom** [comment]
I wanted to add a comment related to this. I ran into this error and it was because I had my samples in groups, and I was testing group A vs group B, but didn't realize that group C had only 1 sample which caused an error even though group A and group B each had more than 1 sample. I assume this is in the fitting of edgeR across all of the groups, before calculating the specific contrast I was interested in. So I got this error. I had to actually run `debug` on the function and go line-by-line to figure out what was going on. 

It would be helpful to have a clearer error message in `pbDS` in the check

```
    if (any(tabulate(y$group_id) < 2) || qr(d)$rank == nrow(d) || 
        qr(d)$rank < ncol(d)) 
      return(NULL)
```

There is no warning message returned here, and therefore it continues on to `.p_adj_global` and returns an entirely uninformative error (and it's not actually an error in `.p_adj_global` at all but the fact that there was a `NULL` calculated because of this problem). It seems like the check on `tabulate(y$group_id) < 2)`  could be done at a higher level and just give an error since every iteration of the for-loop would hit this same error, no? (the other checks on `d` could change across the for-loop so I understand they would have to be done each time).

**Comment by AnjaliC4** [comment]
I have the same issue. It does not seem to be specific to any method. It may have to do with filtering. But if anyone found a solution for this -please let me know.

**Comment by AnjaliC4** [comment]
To answer my own question, this can happen when group_id is confounded with a covariate for a sample. Anyone facing this issue can comment out the lines below which should then throw another error/warning from your differential testing method about the contrast matrix variable that needs possible1 correction.

   if (any(tabulate(y$group_id) < 2) || qr(d)$rank == nrow(d) || 
        qr(d)$rank < ncol(d)) 
      return(NULL)

**Comment by alopehba** [comment]
I meet THE SAME PROBLEM "Error in x[[1]] : subscript out of bounds " . 
2023 now, is there anyone settle it?

**Comment by pariaaliour** [comment]
Hi all,
I ran into the same error when I'm comparing two groups with more than one replicate. Any suggestion how to fix it?
Thanks

**Comment by Siteng999** [comment]
Hi guys,
I seem to understand what's wrong!

First you have to have at least two replicates for each experimental condition and sample_id should be consistent with group_id. For example group_id is ctrl or stim, sample_id is ctrl1 (ctrl rep1),ctrl2(ctrl rep2),stim1 and stim2.

**Comment by HelenaLC** [comment]
Thanks a lot for this! Finally was able to reproduce this in a controlled manner, and implemented a fix as you suggested...

```
# remove empty clusters
rmv <- vapply(res, is.null, logical(1))
res <- res[!rmv]
    
if (length(res) == 0) stop(
  "Specified filtering options result in no genes in any clusters ",
  "being tested. To force testing, consider modifying arguments ",
  "'min_cells' and/or 'filter'. See '?pbDS' for details.")
```

...as opposed to running in an uninformative "subscript out of bounds" error right after. Hope this will makes things clearer for users in the future! (This is on the `devel` branch and should be on Bioc devel within the next couple days, as well as the release with the next cyle.)

**Comment by HelenaLC** [comment]
Yesss, absolutely, that is very sensible! I'll actually wait now for the Bioc build to go through (to see that all is well) before pushing another update. But will follow your suggestion - thanks!
