### ISSUE TITLE
dummy 'kid' variable for whole dataset DE

### ISSUE THREAD

**Issue by lindsaynhayes** [HelenaLC/muscat#80]
Hello muscat masters. 

I would like to contrast the Cell Level mixed Analysis on all the data not on a per cluster basis with the cluster based analysis. I tried the `prepSCE()` without the `kid` term, but it didn't like that. So I added a dummy variable for `kid` to be all the same value for all the cells, then I ran `mmDS`. 
Does this seem like a reasonable approach or will I induce an illegal action or assumption in the mmDS function?

**Comment by HelenaLC** [comment]
Apologies for the very late and probably no-longer useful reply... I think this is fine to do! We have done exactly this [here](https://f1000research.com/articles/6-748) in order to test for global state-changes, i.e., overall differences across groups when being blinded to subpopulations.
