### ISSUE TITLE
Error when simulating data use my own sce object

### ISSUE THREAD

**Issue by wanghao98** [HelenaLC/muscat#84]
Hi, when I tried to perform data simulation using my own sce object, I always encounter an error saying 
`Error in DataFrame(beta0 = cs[, 1], row.names = rownames(x)) :
  invalid length of row names
Calls: prepSim -> DataFrame
`

I tried to check:
1. rownames(sce), which equals to my gene names;
2. my sce contains group_id, sample_id, and cluster_id.

Any idea what might cause the problem and how I may fix it?
Thank you so much!

**Comment by wanghao98** [comment]
Hello, any update on this issue? thanks!

**Comment by HelenaLC** [comment]
Hey, sorry, slipped my mind - thanks for the ping. 

I am actually not sure what is causing the issue. The error occurs in 
```
bs <- DataFrame(
  beta0 = cs[, 1],
  row.names = rownames(x))
```
which is independent of `y`. Both `cs` and `x` are being subset right above via
```
cs <- y$coefficients
i <- !rowAnyNAs(cs)
cs <- cs[i, , drop = FALSE]
x <- x[i, , drop = FALSE]
```
Also, whether or not the input SCE `x` has row names set shouldn't matter, as this is assured in the beginning via
```
if (is.null(rownames(x))) rownames(x) <- paste0("gene", seq(nrow(x)))
if (is.null(colnames(x))) colnames(x) <- paste0("cell", seq(ncol(x)))
```
Would you be able to do look into it via calling `debug("prepSim")`, then rerunning `prepSim(...)` and possible tracking down what's causing this? Currently, I can't reproduce the error with various test cases I tried.

**Comment by wanghao98** [comment]
Hi,
Thank you for looking into this. I'll try your suggestions and see if I may figure out what happens here.
BTW, I tried to walk through the source code and I didn't hit the error. 

However, though bs is independent of Y, when I tried to assign `ds` to x, the length of `ds` is not the same as x so I hit an error as y has not be subset for i. For example, before subsetting, x and y have the same row numbers. But after subsetting, x may have less rows than y while length of ds is the same as y's row number. 
Let me know if I misunderstood anything here.
Thanks!

**Comment by wanghao98** [comment]
Hi, also, I'm not sure if this is an issue of my data or the simulation algorithm. My reference data has 5 samples and 4 clusters. I tried to simulate the data with 10 clusters and 20 samples in each group. Before making changes to the lfc or rel_lfc, the UMAP plot somehow make sense to me. 
![simualte_pca_01DE_10c](https://user-images.githubusercontent.com/25419277/141877488-80a4a35f-b4e4-4c61-935e-f399960fe047.png)

However, when I started to make change to rel_lfc 
![simualte_pca_01DE_10c01rel](https://user-images.githubusercontent.com/25419277/141877546-940eaece-5e1c-4fa9-9842-7bd323c20fd1.png)

and lfc
![simualte_pca_01DE_10c1lfc](https://user-images.githubusercontent.com/25419277/141877547-d504591d-272b-457d-9dad-ca625617cb38.png)
some of the clusters overlapped with each other.

Any idea what those overlap means? Thanks!

**Comment by wanghao98** [comment]
Hello, just want to follow up on my previous post. If I set all the genes to be EE, I would get the following results. I cannot figure out why there would be sub clusters within the same simulated clusters and some of the clusters overlapped with each other.
![image](https://user-images.githubusercontent.com/25419277/144697214-c1ca8815-606e-4bd1-9abe-b687d0164983.png)

**Comment by HelenaLC** [comment]
I would say this is somewhat to be expected. The way the simulation works, simply put, is that every cell belongs to come sample-cluster combination. Now, for every sample-cluster, we sample a reference sample-cluster. In your dataset, there are 5 samples and 4 clusters. Hence for a given cluster, cells can come from one of 5 samples. Hence in the last UMAP above, every cluster is split into 5. This, my intuition says, indicates that the sample-sample differences are of similar magnitude as the cluster-cluster differences. Conversely, is all samples were pretty similar, the clusters shouldn't split in the UMAP. Conversely again, if the clusters were pretty similar, they would overlap but might be split by sample. 

The take home messages for me are: 1) in a reference-based simulation such as this, I would refrain from simulating many more samples and clusters than are available as it can't be avoided that some samples/cluster will be resamples/used more than once; and 2) we aware of how (dis)similar the samples/clusters are in your reference (e.g., what does the non-simulated UMAP look like?) or, in other words, what sample-to-sample/cluster-to-cluster variability is to be expected. As a reference-based simulation will try and mimic the data, these difference will manifest/propagate in the synthetic data.
