### ISSUE TITLE
pbHeatmap doesn't match DS gene list?

### ISSUE THREAD

**Issue by SimoniMD** [HelenaLC/muscat#85]
Hi!

When working through the vignette, I made a list of top DS genes found using pbDS(), but then when I do pbHeatmap() using the result from pbDS(), the genes displayed in the heatmap are different from the genes in  the list. I'm trying to make a heatmap of the genes in the list, separated by cluster and condition. below is the code used. Any idea why? I can force it by making a gene list for the heatmap to use, but just wondering why these would be different by default. Thanks for the help and the great work!

**Comment by HelenaLC** [comment]
Can't see any code.

**Comment by HelenaLC** [comment]
Closing de to inactivity. Feel free to re-open should the issue persist, or to ask further questions in this thread.
