### ISSUE TITLE
Muscat compared to Distinct

### ISSUE THREAD

**Issue by chris-rands** [HelenaLC/muscat#92]
What is the relationship between Muscat and Distinct (https://github.com/SimoneTiberi/distinct)? They seem to do similar things and are from the same research group? Are there recommendations on when to use which tool?

**Comment by markrobinsonuzh** [comment]
Hi @chris-rands 

Indeed, `muscat` pseudobulk (PB) and `distinct` do similar things .. and both from us; we often have multiple ideas and in this case, they both work well. For me, PB has all kinds of other uses, like visualization .. and the results show that it works well to find differences in means, so I would say that it is the standard approach to use. If you are looking to go further, `distinct` should detect all the things that PB detects, but uses the full distribution and should find a "bit more" (if it's there), in terms of changes in the tails of distributions and so on. Probably, `distinct` has a bit higher computational cost, but it's probably not that much.

Hope that helps!

Cheers, Mark
